import{a as b,S as w,i as l}from"./assets/vendor-06b1bbdf.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();async function g(s,t){const r="https://pixabay.com/api/",i="43257905-28a3b58ba6106b31a5e4f67d7",e=new URLSearchParams({key:i,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}),{data:o}=await b(`${r}?${e}`);return o}const p=document.querySelector(".gallery"),L=new w(".gallery a",{captionDelay:250,captionsData:"alt"});function m(s){const t=s.hits.map(({webformatURL:r,largeImageURL:i,tags:e,likes:o,views:n,comments:y,downloads:f})=>`
        <li class="gallery-item">
        <a class="gallery-link" href="${i}">
        <img 
        class="gallery-image"
        src="${r}"
        alt="${e}"/>
        <div class="image-information">
        <p>Likes: ${o}</p>
        <p>Views: ${n}</p>
        <p>Comments: ${y}</p>
        <p>Downloads: ${f}</p>
        </div>
        </a>
        </li>`).join("");p.insertAdjacentHTML("beforeend",t),L.refresh()}const a=document.querySelector(".loader"),C=document.querySelector(".input-field"),d=document.querySelector(".load-more");d.addEventListener("click",v);C.addEventListener("submit",S);let h,u,c;d.classList.add("hidden");a.classList.replace("loader","hidden");async function S(s){if(s.preventDefault(),p.innerHTML="",a.classList.replace("hidden","loader"),u=s.target.elements.designation.value.trim(),c=1,u===""){a.classList.replace("loader","hidden"),l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"red",position:"bottomCenter",iconColor:"white"});return}try{const t=await g(c,u);if(t.totalHits===0){a.classList.replace("loader","hidden"),l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"red",position:"bottomCenter",iconColor:"white"});return}else if(t.totalHits<15){a.classList.replace("loader","hidden"),d.classList.replace("visible","hidden"),l.show({message:"We`re sorry, but you've reached the end of search results.",messageColor:"white",backgroundColor:"green",position:"bottomCenter",iconColor:"white"}),m(t),s.target.reset();return}l.success({iconColor:"yellow",message:"Enjoy watching!",position:"topRight",backgroundColor:"blue",messageColor:"yellow"}),m(t)}catch{l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"red",position:"bottomCenter",iconColor:"white"})}s.target.reset(),d.classList.replace("hidden","visible"),a.classList.replace("loader","hidden")}async function v(){c+=1;try{const r=await g(c,u);h=Math.ceil(r.totalHits/15),console.log(r),m(r),a.classList.replace("hidden","loader"),c>=h&&(a.classList.replace("loader","hidden"),d.classList.replace("visible","hidden"),l.show({message:"We`re sorry, but you've reached the end of search results.",messageColor:"white",backgroundColor:"green",position:"bottomCenter",iconColor:"white"}))}catch(r){alert(r.message)}const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:t*2,behavior:"smooth"}),a.classList.replace("loader","hidden")}
//# sourceMappingURL=commonHelpers.js.map
